### ISSUE TITLE
ooh

### ISSUE THREAD

**Issue by LankyBox01** [jeffalo/griffbot-verify#4]
so you do discord bots?

**Comment by jeffalo** [comment]
yeah. this is a bot i made to make modration a little easier on a discord server

**Comment by LankyBox01** [comment]
I also made a discord bot. It's called holybot. It's basically an economy bot with holy characteristics.
I unfortunately discontinued it, but i will make the source code public soon

**Comment by Quantum-Codes** [comment]
Whats the server link?

**Comment by jeffalo** [comment]
> Whats the server link?

sorry, i can't share it because i like being able to link my github on scratch.
